[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "arbitrage_bot"
version = "0.1.0"
authors = [
    { name = "Your Name", email = "your.email@example.com" },
]
description = "Arbitrage trading bot for Base network"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "flask-socketio",
    "eventlet",
    "cryptography",
    "flask-cors",
    "web3>=7.0.0",
    "eth-tester",

    "python-dotenv>=1.0.0",
    "aiohttp>=3.8.0",
    "asyncio",
    "websockets>=10.0",
    "requests",
    "pandas",
    "numpy",
    "scikit-learn",
    "joblib",
    "sqlalchemy",
    "psycopg2-binary",
    "redis",
    "aioredis",
    "prometheus_client",
    "pyyaml",
    "jsonschema",
]

[tool.setuptools]
packages = ["arbitrage_bot"]
package-dir = { "" = "." }

[tool.setuptools.package-data]
arbitrage_bot = ["configs/*.json", "abi/*.json"]
