from setuptools import setup, find_packages

setup(
    name="arbitrage_bot",
    version="0.1.0",
    description="Listonian Bot - Advanced arbitrage trading system for DEXs",
    author="Listonian Team",
    author_email="team@listonian-bot.com",
    url="https://github.com/your-organization/Listonian-bot",
    packages=find_packages(),
    install_requires=[
        "web3>=6.0.0",
        "fastapi>=0.95.0",
        "uvicorn>=0.21.0",
        "pydantic>=1.10.7",
        "python-dotenv>=1.0.0",
        "requests>=2.28.2",
        "aiohttp>=3.8.4",
        "networkx>=3.0",
        "pandas>=2.0.0",
        "numpy>=1.24.2",
        "matplotlib>=3.7.1",
        "pytest>=7.3.1",
        "pytest-cov>=4.1.0",
        "black>=23.3.0",
        "isort>=5.12.0",
        "flake8>=6.0.0",
        "mypy>=1.3.0",
    ],
    extras_require={
        "dev": [
            "pytest>=7.3.1",
            "pytest-cov>=4.1.0",
            "black>=23.3.0",
            "isort>=5.12.0",
            "flake8>=6.0.0",
            "mypy>=1.3.0",
            "pre-commit>=3.3.1",
        ],
    },
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Financial and Insurance Industry",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
    python_requires=">=3.9",
)
