@echo off
echo Starting bot API server...
start cmd /k python bot_api_server.py
echo Waiting for API server to start...
timeout /t 3 /nobreak > nul
echo Starting dashboard...
python serve_real_data_dashboard.py
pause
